#!/bin/bash

echo "Enter number of processes:"
read n

echo "Enter burst times:"
read -a bt

wt[0]=0
tat[0]=${bt[0]}

for ((i=1; i<n; i++))
do
    wt[$i]=$((wt[i-1] + bt[i-1]))
    tat[$i]=$((wt[i] + bt[i]))
done

echo "Process  BT  WT  TAT"

for ((i=0; i<n; i++))
do
    echo "P$((i+1))    ${bt[i]}    ${wt[i]}    ${tat[i]}"
done
