#!/bin/bash

echo "Enter number of processes:"
read n

for ((i=0; i<n; i++))
do
    p[$i]=$((i+1))

    echo "Enter burst time for P$((i+1)):"
    read bt[$i]

    echo "Enter priority for P$((i+1)):"
    read priority[$i]
done

for ((i=0; i<n-1; i++))
do
    for ((j=i+1; j<n; j++))
    do
        if [ ${priority[i]} -gt ${priority[j]} ]
        then
            temp=${priority[i]}
            priority[$i]=${priority[j]}
            priority[$j]=$temp

            temp=${bt[i]}
            bt[$i]=${bt[j]}
            bt[$j]=$temp

            temp=${p[i]}
            p[$i]=${p[j]}
            p[$j]=$temp
        fi
    done
done

wt[0]=0

for ((i=1; i<n; i++))
do
    wt[$i]=$((wt[i-1] + bt[i-1]))
done

echo "Process  BT  Priority  WT"

for ((i=0; i<n; i++))
do
    echo "P${p[i]}    ${bt[i]}    ${priority[i]}    ${wt[i]}"
done
